### ISSUE TITLE
egl mouse position not pinned to screen/window size

### ISSUE THREAD

**Issue by johnrobinsn** [johnrobinsn/pxCore#15]

**Comment by gladish** [comment]
The EGL layer doesn't know about the position of the mouse. It just knows when relative movement on x/y axis.  Right now the actual mouse position is handled in the load.js. 

We probably need to build into the pxWindow the capability to draw and track the position of a cursor.

**Comment by johnrobinsn** [comment]
I don't think so... I think at EGL layer we can know the screen size...
might be platform specific (so in the provider)...

And at EGL layer we are sending events for mouse location so we are
tracking the mouse location at the EGL layer... we just need to "pin it" to
the screen size...

JR
