### ISSUE TITLE
egl onchar event not working

### ISSUE THREAD

**Issue by johnrobinsn** [johnrobinsn/pxCore#16]

**Comment by gladish** [comment]
What are the semantics for onChar? Is that invoked just once for keydown or is it repeat? Is SHIFT applied to character? I.e. is shift-c is 'c' passed or 'C'?

**Comment by johnrobinsn** [comment]
Jake did you get a chance to do anything with this?  

Yes shift is applied... 
Yes onChar is repeated...  for now ok to emulate what's there for glut...
