### ISSUE TITLE
Stretch options do not work with constructor only

### ISSUE THREAD

**Issue by bobseamon** [johnrobinsn/pxCore#20]
If I supply all needed args in createImage, FILL or STRETCH options do not work.

```javascript
var imgurl = process.cwd() + "/../../images/banana.png";
var image = scene.createImage({url:imgurl, parent:root, xStretch:2, yStretch:2, w:800, h:400,});
```

But if I supply w and h after construction, FILL and STRETCH work fine.

```javascript
var imgurl = process.cwd() + "/../../images/banana.png";
var image = scene.createImage({url:imgurl, parent:root, xStretch:2, yStretch:2});
image.w = scene.w;
image.h = scene.h;
```
I should be able to pass all arguments to constructor without the need to supply additional setters later.

**Comment by cfry002** [comment]
I am finding a similar issue when trying to set width in the createImage9() constructor.  I would have thought that the image should respect the constructor parms values in this regard, but when the image is loaded from a remote location, the values are not being respected.

**Comment by johnrobinsn** [comment]
Set autoSize to false... We can discuss alternatives

**Comment by cfry002** [comment]
Unfortunately, setting autoSize does not seem to affect the behavior. I still see the same issue.

**Comment by cfry002** [comment]
As part of API_review changes, autoSize was deprecated in favor of using resource h/w when the pxImage h/w are not set (they default to -1).  The values set on construction as in the example will now work as expected.
