### ISSUE TITLE
Get rid of animateTo method with function callback

### ISSUE THREAD

**Issue by johnrobinsn** [johnrobinsn/pxCore#24]
we only want to support the animateTo variant that returns a promise.  that variant should be renamed from animateToP back to just animateTo...   there will be a number of samples that need to be fixed up...

**Comment by mfiess** [comment]
animateTo now supports promises.  I renamed the old animateTo to animateToF for the short term (and updated all the old function animateTo method calls to animateToF) until all the samples are converted over to use promises.  The following samples have been converted over to use the new animateTo promise version: fancyp.js, mask_with_objects_test.js, picturepile.js, and promise.js.  All other scripts have moved to animateToF.  I'm in the midst of updating those samples to use the promise version now, and they will be committed within a days time.

**Comment by mfiess** [comment]
All the samples are now updated to use the promise version of animateTo().  animateToF() is no longer needed, and I will remove.

**Comment by mfiess** [comment]
Removed animateToF()
