### ISSUE TITLE
Add ready promise property to all pxObjects

### ISSUE THREAD

**Issue by johnrobinsn** [johnrobinsn/pxCore#25]
all pxObjects should have the concept of readiness... some objects will be immediately ready.. .but any that have dependencies should defer readiness until all resources required to render and size are available.

In addition, canonicalize error state details...

**Comment by mfiess** [comment]
The ready promise property is now available for all pxObjects.  I updated pxImage, pxImage9, pxRect, and pxText to set the promise property on ready or failure.

**Comment by cfry002** [comment]
I think this one is done now.
