### ISSUE TITLE
Build on Raspberry Pi

### ISSUE THREAD

**Issue by ColorfullyMe** [johnrobinsn/pxCore#253]
https://github.com/johnrobinsn/pxCore/blob/master/examples/pxScene2d/README.md#on-raspberry-pi

Hi, is this type error in step 4.?
There is no file named `Makefile.egl` in pxCore root.
Should we assume to use `Makefile.glut` on RPi too?
Thanks

**Comment by johnrobinsn** [comment]
Tweaked instructions...  located in ~/pxCore/src
