### ISSUE TITLE
Add an onFocus event to pxObject

### ISSUE THREAD

**Issue by johnrobinsn** [johnrobinsn/pxCore#26]
The onFocus should contain a boolean flag that indicates that focus was gained or lost.  Only one object within a given scene can have focus at any given time. when focus changes and onFocus(lost) must be sent to the object that is losing focus... and onFocus(gained) must be sent to the object gaining focus...

**Comment by cfry002** [comment]
I actually just implemented something like this in order to get my prototype working correctly. :-)  I implemented onFocus and onBlur because I couldn't find anything like that in the existing code. Maybe I just missed it.  In any case, I can share my code, or we can discuss.

**Comment by johnrobinsn** [comment]
sounds good.... fork pxCore and check your code in there... and submit a
pull request

**Comment by cfry002** [comment]
Pull request has been submitted.

**Comment by cfry002** [comment]
Are you good with the implementation for this as it is now, so that we can close this issue? As I recall, you weren't sure about the nomenclature I used.

**Comment by cfry002** [comment]
Implemented.  Closing this issue.
