### ISSUE TITLE
Add Screen Capture functionality

### ISSUE THREAD

**Issue by bobseamon** [johnrobinsn/pxCore#31]
Required for QA and support functionality.

**Comment by johnrobinsn** [comment]
What file format is required?

**Comment by bobseamon** [comment]
.png

**Comment by johnrobinsn** [comment]
committed to the _temp_shader_breakout branch... Mike should be merging back to _temp_pxcore2_stage soon

**Comment by johnrobinsn** [comment]
Bob is this done yet? Thanks

**Comment by cfry002** [comment]
screenshot has been added to pxScene
