### ISSUE TITLE
text.h is incorrect with newline character

### ISSUE THREAD

**Issue by bobseamon** [johnrobinsn/pxCore#32]
```javascript
var text1 = scene.create({t:"text", textColor:0xFF0000FF, pixelSize:20, parent:root, x:50, y:50, text:"just a single line of text" });
console.log("text1.h: ", text1.h);
var text2 = scene.create({t:"text", textColor:0xFF0000FF, pixelSize:20, parent:root, x:50, y:100, text:"text\n spread\n out\n over\n multiple\n lines" });
console.log("text2.h: ", text2.h);
```
Output:
text1.h:  34
text2.h:  10914

text2.h should be closer to 204

**Comment by cfry002** [comment]
I believe line 184 in pxText.cpp needs to be commented in and line 185 commented out.  It needs the >>6 to get the correct value for resolution/platform. 
h += metrics->height>>6;

**Comment by johnrobinsn** [comment]
Connie can you go ahead and take care of that...

Thanks

**Comment by cfry002** [comment]
Fix has been checked in.
