### ISSUE TITLE
When the mask url is reset( when set to null and again set with the previous url), the mask is not set. 

### ISSUE THREAD

**Issue by cfry002** [johnrobinsn/pxCore#37]
If set to use a new URL, the mask is set correctly.  But if using an URL that was previously used, the mask is not set.  

Example:
var root =  scene.root;
var view = scene.create({t:"object", parent:root, w:500, h:500});
var url = process.cwd() + "/../../images/postermask.png";
var urlTest = process.cwd() + "/../../images/ball.png";
var bgShade = scene.createImage({url:urlTest, xStretch:1, yStretch:1, parent:view});
view.mask = url;
setTimeout(function(){
    console.log("setTimeout >>> Set mask to null ");
    view.mask = null;
},5000);
setTimeout(function(){
    console.log("setTimeout >>> Set mask to " + url);
	view.mask = url;
},10000);

**Comment by johnrobinsn** [comment]
I think we want the mask=url form to go away...  Can we add this to the tata list to switch to the mask layers form... Fiess has the details...

**Comment by cfry002** [comment]
This task has been moved to Jira.  Closing...
