### ISSUE TITLE
rvValue support for unsigned long

### ISSUE THREAD

**Issue by gladish** [johnrobinsn/pxCore#7]
The px API uses unsigned long types in some places which means the rtValue will need to support it. We should either add support for unsigned long to rvValue or not use unsigned long. I would be in favor using sized types only (int32_t, int64_t, etc) throughout the px/rt and other APIs to ensure portability and avoid any type conversion problems.

**Comment by johnrobinsn** [comment]
agree... I thik adding explicit support for int64_t and uint64_t to rtValue will be sufficient

**Comment by gladish** [comment]
rvValue now has int64_t and uint64_t.
